### ISSUE TITLE
Fingerprint wrong related to issue #22

### ISSUE THREAD

**Issue by CHENPINGFIONA** [muhdfirdaus/NTUC-API#23]
Related issue #22  
https://github.com/muhdfirdaus/NTUC-API/blame/master/public_html/index.php#L73
Format of finger print  /api/updates/ short of "/"

**Comment by josergcatmisatravelcom** [comment]
Don't hard code the "api/updates" in the "fp" function. Instead, get the resource URI from the request.

Modify your function to accept "method" and "resourceUri" and replace the hard coded values

<pre>
function fp($apikey, $secret, $timestamp, $nric, $amount, $date, $source, $method, $resourceUri){
  return hash('sha256', $apikey. "," . $secret. "," .$timestamp.",$method,$resourceUri,nric=".$nric."&amount=".$amount."&date=".$date."&source=".$source );
}
</pre>

then modify the place from where this function is called

<pre>
...
$resourceUri = $app->request->getResourceUri();
...
$fp = fp($apiKey, $secret, $timestamp, $nric, $amount, $date, $source, 'POST', $resourceUri);
</pre>

So that, you can reuse this "fp" function later in other requests.

**Comment by josergcatmisatravelcom** [comment]
I have taken a look and the current implementation 4780e592f90ba10c9c20900810cc91dfc8570a46 and the function is wrong

<pre>
function fp($apikey, $secret, $timestamp, $nric, $amount, $date, $source, $method, $resourceUri){
        $fp = hash('sha256', $apikey. "," . $secret. "," .$timestamp."," . $method . "," . $resourceUri . "nric=".$nric."&amount=".$amount."&date=".$date."&source=".$source );
        return $fp;
}
</pre>

Notice in <pre>$resourceUri . "nric=".$nric</pre> you are missing a comma (,) . It must be <pre>$resourceUri . ",nric=".$nric</pre>
